server:
  port: 9000
logging:
  file:
    name: D:/Project-Spring/log-microservice/log/gateway.log
    pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n'
  logback:
    rolling policy:
      max-history: 7
      total-size-cap: 0
eureka:
  client:
    enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: Authentication
        - id: ProductService
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/product/**
          filters:
            - name: Authentication
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
