spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/schemas_user?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: dungbadao2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true

  application:
    name: UserService
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9002

jwt:
  secret: Zing
  token:
    expire:
      time: 300

  # absolute path
logging:
  file:
    name: D:/Project-Spring/log-microservice/log/user-service.log
    pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n'
  logback:
    rolling policy:
      max-history: 7
      total-size-cap: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'
        # include: health,prometheus,metrics