spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/product?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: dungbadao2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true

  application:
    name: ProductService
  kafka:
    bootstrap-server: localhost:9092
    auto-commit-interval: 100
    session-timeout: 45000
    auto-offset-reset: earliest
    max-poll-record: 1
    order-topic: ORDER-CONTROL
    userName: admin
    passWord: Dg4cOP1c/puFhUmVrZVnSw==
    enableUserPass: false
    encryptKey: cApTPxTMGVVf5vrM
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9003

logging:
  file:
    name: D:/Project-Spring/log-microservice/log/product-service.log
    pattern:
      file: '%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n'
  logback:
    rolling policy:
      max-history: 7
      total-size-cap: 0